# Generated by Django 4.1 on 2022-11-25 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_company_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_employees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDevices',
            fields=[
                ('devices', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='get_employees', serialize=False, to='company_app.companydevice')),
                ('checked_out', models.DateTimeField(auto_now_add=True)),
                ('returned', models.DateTimeField(null=True)),
                ('log', models.CharField(choices=[('fresh', 'FRESH'), ('break', 'Break'), ('refurbish', 'REFURBISH')], max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_employee_devices', to='company_app.employee')),
            ],
        ),
    ]
