# Generated by Django 4.1 on 2022-11-26 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0006_alter_employeedevices_devices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedevices',
            name='devices',
            field=models.OneToOneField(limit_choices_to=models.Q(('company__id', 'company')), on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='get_employees', serialize=False, to='company_app.companydevice'),
        ),
        migrations.AlterField(
            model_name='employeedevices',
            name='employee',
            field=models.ForeignKey(limit_choices_to=models.Q(('company__id', 'company')), on_delete=django.db.models.deletion.CASCADE, related_name='get_employee_devices', to='company_app.employee'),
        ),
    ]
