# Generated by Django 4.1 on 2022-11-26 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_app', '0010_alter_employeedevices_devices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedevices',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_employee_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
