# Generated by Django 4.1 on 2022-11-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0011_alter_employeedevices_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedevices',
            old_name='devices',
            new_name='device',
        ),
    ]
