# Generated by Django 4.1 on 2022-11-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0012_rename_devices_employeedevices_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedevices',
            name='log',
        ),
        migrations.CreateModel(
            name='EmployeeDeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_employee_device_logs', to='company_app.employeedevices')),
            ],
        ),
    ]
